export enum Port {
  LIBFPTR_PORT_COM = 0,
  LIBFPTR_PORT_USB,
  LIBFPTR_PORT_TCPIP,
  LIBFPTR_PORT_BLUETOOTH,
}

export interface Settings {
    AccessPassword: string;
    AutoDisableBluetooth: boolean;
    AutoEnableBluetooth: boolean;
    AutoReconnect: boolean;
    BaudRate: number;
    Bits: number;
    ComFile: string;
    DocumentsJournalPath: string;
    IPAddress: string;
    IPPort: number;
    InvertCashDrawerStatus: boolean;
    LibraryPath: string;
    MACAddress: string;
    Model: number;
    OfdChannel: number;
    Parity: number;
    Port: Port;
    RemoteServerAddr: string;
    RemoteServerConnectionTimeout: number;
    ScriptsPath: string;
    StopBits: number;
    UsbDevicePath: string;
    UseDocumentsJournal: boolean;
    UserPassword: string;
}
export interface LastDocument {
    documentNumber: number;
    fiscalSign: string;
    date: {
        year: number;
        month: number;
        day: number;
        hour: number;
        minute: number;
        second: number;
    };
}
export interface DeviceInfo {
    configurationVersion: string;
    ecrFfdVersion: string;
    fnFfdVersion: string;
    firmwareVersion: string;
    model: number;
    modelName: string;
    receiptLineLength: number;
    receiptLineLengthPx: number;
    serial: string;
}
export declare class Fptr10 {
    create(): void;
    isOpened(): boolean;
    destroy(): void;
    getSettings(): Settings;
    setSettings(settings: Settings): boolean;
    open(): boolean;
    close(): boolean;
    processJson(json: unknown): any;
    processJsonAsync(json: unknown, cb: (error: any, result: any) => void): void;
    fnReport(type: number): any;
    findLastDocument(): LastDocument;
}

export enum ERROR {
    LIBFPTR_OK = 0,
    LIBFPTR_ERROR_CONNECTION_DISABLED,
    LIBFPTR_ERROR_NO_CONNECTION,
    LIBFPTR_ERROR_PORT_BUSY,
    LIBFPTR_ERROR_PORT_NOT_AVAILABLE,
    LIBFPTR_ERROR_INCORRECT_DATA,
    LIBFPTR_ERROR_INTERNAL,
    LIBFPTR_ERROR_UNSUPPORTED_CAST,
    LIBFPTR_ERROR_NO_REQUIRED_PARAM,
    LIBFPTR_ERROR_INVALID_SETTINGS,
    LIBFPTR_ERROR_NOT_CONFIGURED,
    LIBFPTR_ERROR_NOT_SUPPORTED,
    LIBFPTR_ERROR_INVALID_MODE,
    LIBFPTR_ERROR_INVALID_PARAM,
    LIBFPTR_ERROR_NOT_LOADED,
    LIBFPTR_ERROR_UNKNOWN,

    LIBFPTR_ERROR_INVALID_SUM,
    LIBFPTR_ERROR_INVALID_QUANTITY,
    LIBFPTR_ERROR_CASH_COUNTER_OVERFLOW,
    LIBFPTR_ERROR_LAST_OPERATION_STORNO_DENIED,
    LIBFPTR_ERROR_STORNO_BY_CODE_DENIED,
    LIBFPTR_ERROR_LAST_OPERATION_NOT_REPEATABLE,
    LIBFPTR_ERROR_DISCOUNT_NOT_REPEATABLE,
    LIBFPTR_ERROR_DISCOUNT_DENIED,
    LIBFPTR_ERROR_INVALID_COMMODITY_CODE,
    LIBFPTR_ERROR_INVALID_COMMODITY_BARCODE,
    LIBFPTR_ERROR_INVALID_COMMAND_FORMAT,
    LIBFPTR_ERROR_INVALID_COMMAND_LENGTH,
    LIBFPTR_ERROR_BLOCKED_IN_DATE_INPUT_MODE,
    LIBFPTR_ERROR_NEED_DATE_ACCEPT,
    LIBFPTR_ERROR_NO_MORE_DATA,
    LIBFPTR_ERROR_NO_ACCEPT_OR_CANCEL,
    LIBFPTR_ERROR_BLOCKED_BY_REPORT_INTERRUPTION,
    LIBFPTR_ERROR_DISABLE_CASH_CONTROL_DENIED,
    LIBFPTR_ERROR_MODE_BLOCKED,
    LIBFPTR_ERROR_CHECK_DATE_TIME,
    LIBFPTR_ERROR_DATE_TIME_LESS_THAN_FS,
    LIBFPTR_ERROR_CLOSE_ARCHIVE_DENIED,
    LIBFPTR_ERROR_COMMODITY_NOT_FOUND,
    LIBFPTR_ERROR_WEIGHT_BARCODE_WITH_INVALID_QUANTITY,
    LIBFPTR_ERROR_RECEIPT_BUFFER_OVERFLOW,
    LIBFPTR_ERROR_QUANTITY_TOO_FEW,
    LIBFPTR_ERROR_STORNO_TOO_MUCH,
    LIBFPTR_ERROR_BLOCKED_COMMODITY_NOT_FOUND,
    LIBFPTR_ERROR_NO_PAPER,
    LIBFPTR_ERROR_COVER_OPENED,
    LIBFPTR_ERROR_PRINTER_FAULT,
    LIBFPTR_ERROR_MECHANICAL_FAULT,
    LIBFPTR_ERROR_INVALID_RECEIPT_TYPE,
    LIBFPTR_ERROR_INVALID_UNIT_TYPE,
    LIBFPTR_ERROR_NO_MEMORY,
    LIBFPTR_ERROR_PICTURE_NOT_FOUND,
    LIBFPTR_ERROR_NONCACH_PAYMENTS_TOO_MUCH,
    LIBFPTR_ERROR_RETURN_DENIED,
    LIBFPTR_ERROR_PAYMENTS_OVERFLOW,
    LIBFPTR_ERROR_BUSY,
    LIBFPTR_ERROR_GSM,
    LIBFPTR_ERROR_INVALID_DISCOUNT,
    LIBFPTR_ERROR_OPERATION_AFTER_DISCOUNT_DENIED,
    LIBFPTR_ERROR_INVALID_DEPARTMENT,
    LIBFPTR_ERROR_INVALID_PAYMENT_TYPE,
    LIBFPTR_ERROR_MULTIPLICATION_OVERFLOW,
    LIBFPTR_ERROR_DENIED_BY_SETTINGS,
    LIBFPTR_ERROR_TOTAL_OVERFLOW,
    LIBFPTR_ERROR_DENIED_IN_ANNULATION_RECEIPT,
    LIBFPTR_ERROR_JOURNAL_OVERFLOW,
    LIBFPTR_ERROR_NOT_FULLY_PAID,
    LIBFPTR_ERROR_DENIED_IN_RETURN_RECEIPT,
    LIBFPTR_ERROR_SHIFT_EXPIRED,
    LIBFPTR_ERROR_DENIED_IN_SELL_RECEIPT,
    LIBFPTR_ERROR_FISCAL_MEMORY_OVERFLOW,
    LIBFPTR_ERROR_INVALID_PASSWORD,
    LIBFPTR_ERROR_JOURNAL_BUSY,
    LIBFPTR_ERROR_DENIED_IN_CLOSED_SHIFT,
    LIBFPTR_ERROR_INVALID_TABLE_NUMBER,
    LIBFPTR_ERROR_INVALID_ROW_NUMBER,
    LIBFPTR_ERROR_INVALID_FIELD_NUMBER,
    LIBFPTR_ERROR_INVALID_DATE_TIME,
    LIBFPTR_ERROR_INVALID_STORNO_SUM,
    LIBFPTR_ERROR_CHANGE_CALCULATION,
    LIBFPTR_ERROR_NO_CASH,
    LIBFPTR_ERROR_DENIED_IN_CLOSED_RECEIPT,
    LIBFPTR_ERROR_DENIED_IN_OPENED_RECEIPT,
    LIBFPTR_ERROR_DENIED_IN_OPENED_SHIFT,
    LIBFPTR_ERROR_SERIAL_NUMBER_ALREADY_ENTERED,
    LIBFPTR_ERROR_TOO_MUCH_REREGISTRATIONS,
    LIBFPTR_ERROR_INVALID_SHIFT_NUMBER,
    LIBFPTR_ERROR_INVALID_SERIAL_NUMBER,
    LIBFPTR_ERROR_INVALID_RNM_VATIN,
    LIBFPTR_ERROR_FISCAL_PRINTER_NOT_ACTIVATED,
    LIBFPTR_ERROR_SERIAL_NUMBER_NOT_ENTERED,
    LIBFPTR_ERROR_NO_MORE_REPORTS,
    LIBFPTR_ERROR_MODE_NOT_ACTIVATED,
    LIBFPTR_ERROR_RECORD_NOT_FOUND_IN_JOURNAL,
    LIBFPTR_ERROR_INVALID_LICENSE,
    LIBFPTR_ERROR_NEED_FULL_RESET,
    LIBFPTR_ERROR_DENIED_BY_LICENSE,
    LIBFPTR_ERROR_DISCOUNT_CANCELLATION_DENIED,
    LIBFPTR_ERROR_CLOSE_RECEIPT_DENIED,
    LIBFPTR_ERROR_INVALID_ROUTE_NUMBER,
    LIBFPTR_ERROR_INVALID_START_ZONE_NUMBER,
    LIBFPTR_ERROR_INVALID_END_ZONE_NUMBER,
    LIBFPTR_ERROR_INVALID_RATE_TYPE,
    LIBFPTR_ERROR_INVALID_RATE,
    LIBFPTR_ERROR_FISCAL_MODULE_EXCHANGE,
    LIBFPTR_ERROR_NEED_TECHNICAL_SUPPORT,
    LIBFPTR_ERROR_SHIFT_NUMBERS_DID_NOT_MATCH,
    LIBFPTR_ERROR_DEVICE_NOT_FOUND,
    LIBFPTR_ERROR_EXTERNAL_DEVICE_CONNECTION,
    LIBFPTR_ERROR_DISPENSER_INVALID_STATE,
    LIBFPTR_ERROR_INVALID_POSITIONS_COUNT,
    LIBFPTR_ERROR_DISPENSER_INVALID_NUMBER,
    LIBFPTR_ERROR_INVALID_DIVIDER,
    LIBFPTR_ERROR_FN_ACTIVATION_DENIED,
    LIBFPTR_ERROR_PRINTER_OVERHEAT,
    LIBFPTR_ERROR_FN_EXCHANGE,
    LIBFPTR_ERROR_FN_INVALID_FORMAT,
    LIBFPTR_ERROR_FN_INVALID_STATE,
    LIBFPTR_ERROR_FN_FAULT,
    LIBFPTR_ERROR_FN_CRYPTO_FAULT,
    LIBFPTR_ERROR_FN_EXPIRED,
    LIBFPTR_ERROR_FN_OVERFLOW,
    LIBFPTR_ERROR_FN_INVALID_DATE_TIME,
    LIBFPTR_ERROR_FN_NO_MORE_DATA,
    LIBFPTR_ERROR_FN_TOTAL_OVERFLOW,
    LIBFPTR_ERROR_BUFFER_OVERFLOW,
    LIBFPTR_ERROR_PRINT_SECOND_COPY_DENIED,
    LIBFPTR_ERROR_NEED_RESET_JOURNAL,
    LIBFPTR_ERROR_TAX_SUM_TOO_MUCH,
    LIBFPTR_ERROR_TAX_ON_LAST_OPERATION_DENIED,
    LIBFPTR_ERROR_INVALID_FN_NUMBER,
    LIBFPTR_ERROR_TAX_CANCEL_DENIED,
    LIBFPTR_ERROR_LOW_BATTERY,
    LIBFPTR_ERROR_FN_INVALID_COMMAND,
    LIBFPTR_ERROR_FN_COMMAND_OVERFLOW,
    LIBFPTR_ERROR_FN_NO_TRANSPORT_CONNECTION,
    LIBFPTR_ERROR_FN_CRYPTO_HAS_EXPIRED,
    LIBFPTR_ERROR_FN_RESOURCE_HAS_EXPIRED,
    LIBFPTR_ERROR_INVALID_MESSAGE_FROM_OFD,
    LIBFPTR_ERROR_FN_HAS_NOT_SEND_DOCUMENTS,
    LIBFPTR_ERROR_FN_TIMEOUT,
    LIBFPTR_ERROR_FN_SHIFT_EXPIRED,
    LIBFPTR_ERROR_FN_INVALID_TIME_DIFFERENCE,
    LIBFPTR_ERROR_INVALID_TAXATION_TYPE,
    LIBFPTR_ERROR_INVALID_TAX_TYPE,
    LIBFPTR_ERROR_INVALID_COMMODITY_PAYMENT_TYPE,
    LIBFPTR_ERROR_INVALID_COMMODITY_CODE_TYPE,
    LIBFPTR_ERROR_EXCISABLE_COMMODITY_DENIED,
    LIBFPTR_ERROR_FISCAL_PROPERTY_WRITE,
    LIBFPTR_ERROR_INVALID_COUNTER_TYPE,
    LIBFPTR_ERROR_CUTTER_FAULT,
    LIBFPTR_ERROR_REPORT_INTERRUPTED,
    LIBFPTR_ERROR_INVALID_LEFT_MARGIN,
    LIBFPTR_ERROR_INVALID_ALIGNMENT,
    LIBFPTR_ERROR_INVALID_TAX_MODE,
    LIBFPTR_ERROR_FILE_NOT_FOUND,
    LIBFPTR_ERROR_PICTURE_TOO_BIG,
    LIBFPTR_ERROR_INVALID_BARCODE_PARAMS,
    LIBFPTR_ERROR_FISCAL_PROPERTY_DENIED,
    LIBFPTR_ERROR_FN_INTERFACE,
    LIBFPTR_ERROR_DATA_DUPLICATE,
    LIBFPTR_ERROR_NO_REQUIRED_FISCAL_PROPERTY,
    LIBFPTR_ERROR_FN_READ_DOCUMENT,
    LIBFPTR_ERROR_FLOAT_OVERFLOW,
    LIBFPTR_ERROR_INVALID_SETTING_VALUE,
    LIBFPTR_ERROR_HARD_FAULT,
    LIBFPTR_ERROR_FN_NOT_FOUND,
    LIBFPTR_ERROR_INVALID_AGENT_FISCAL_PROPERTY,
    LIBFPTR_ERROR_INVALID_FISCAL_PROPERTY_VALUE_1002_1056,
    LIBFPTR_ERROR_INVALID_FISCAL_PROPERTY_VALUE_1002_1017,
    LIBFPTR_ERROR_SCRIPT,
    LIBFPTR_ERROR_INVALID_USER_MEMORY_INDEX,
    LIBFPTR_ERROR_NO_ACTIVE_OPERATOR,
    LIBFPTR_ERROR_REGISTRATION_REPORT_INTERRUPTED,
    LIBFPTR_ERROR_CLOSE_FN_REPORT_INTERRUPTED,
    LIBFPTR_ERROR_OPEN_SHIFT_REPORT_INTERRUPTED,
    LIBFPTR_ERROR_OFD_EXCHANGE_REPORT_INTERRUPTED,
    LIBFPTR_ERROR_CLOSE_RECEIPT_INTERRUPTED,
    LIBFPTR_ERROR_FN_QUERY_INTERRUPTED,
    LIBFPTR_ERROR_RTC_FAULT,
    LIBFPTR_ERROR_MEMORY_FAULT,
    LIBFPTR_ERROR_CHIP_FAULT,
    LIBFPTR_ERROR_TEMPLATES_CORRUPTED,
    LIBFPTR_ERROR_INVALID_MAC_ADDRESS,
    LIBFPTR_ERROR_INVALID_SCRIPT_NUMBER,
    LIBFPTR_ERROR_SCRIPTS_FAULT,
    LIBFPTR_ERROR_INVALID_SCRIPTS_VERSION,
    LIBFPTR_ERROR_INVALID_CLICHE_FORMAT,
    LIBFPTR_ERROR_WAIT_FOR_REBOOT,
    LIBFPTR_ERROR_NO_LICENSE,
    LIBFPTR_ERROR_INVALID_FFD_VERSION,
    LIBFPTR_ERROR_CHANGE_SETTING_DENIED,
    LIBFPTR_ERROR_INVALID_NOMENCLATURE_TYPE,
    LIBFPTR_ERROR_INVALID_GTIN,
    LIBFPTR_ERROR_NEGATIVE_MATH_RESULT,
    LIBFPTR_ERROR_FISCAL_PROPERTIES_COMBINATION,
    LIBFPTR_ERROR_OPERATOR_LOGIN,
    LIBFPTR_ERROR_INVALID_INTERNET_CHANNEL,
    LIBFPTR_ERROR_DATETIME_NOT_SYNCRONIZED,
    LIBFPTR_ERROR_JOURNAL,
    LIBFPTR_ERROR_DENIED_IN_OPENED_DOC,
    LIBFPTR_ERROR_DENIED_IN_CLOSED_DOC,
    LIBFPTR_ERROR_LICENSE_MEMORY_OVERFLOW,
    LIBFPTR_ERROR_NEED_CANCEL_DOCUMENT,
    LIBFPTR_ERROR_REGISTERS_NOT_INITIALIZED,
    LIBFPTR_ERROR_TOTAL_REQUIRED,
    LIBFPTR_ERROR_SETTINGS_FAULT,
    LIBFPTR_ERROR_COUNTERS_FAULT,
    LIBFPTR_ERROR_USER_MEMORY_FAULT,
    LIBFPTR_ERROR_SERVICE_COUNTERS_FAULT,
    LIBFPTR_ERROR_ATTRIBUTES_FAULT,
    LIBFPTR_ERROR_ALREADY_IN_UPDATE_MODE,
    LIBFPTR_ERROR_INVALID_FIRMWARE,
    LIBFPTR_ERROR_INVALID_CHANNEL,
    LIBFPTR_ERROR_INTERFACE_DOWN,
    LIBFPTR_ERROR_INVALID_FISCAL_PROPERTY_VALUE_1212_1030,
    LIBFPTR_ERROR_INVALID_FISCAL_PROPERTY_VALUE_1214,
    LIBFPTR_ERROR_INVALID_FISCAL_PROPERTY_VALUE_1212,
    LIBFPTR_ERROR_SYNC_TIME,
    LIBFPTR_ERROR_VAT18_VAT20_IN_RECEIPT,
    LIBFPTR_ERROR_PICTURE_NOT_CLOSED,
    LIBFPTR_ERROR_INTERFACE_BUSY,
    LIBFPTR_ERROR_INVALID_PICTURE_NUMBER,
    LIBFPTR_ERROR_INVALID_CONTAINER,
    LIBFPTR_ERROR_ARCHIVE_CLOSED,
    LIBFPTR_ERROR_NEED_REGISTRATION,
    LIBFPTR_ERROR_DENIED_DURING_UPDATE,
    LIBFPTR_ERROR_INVALID_TOTAL,
    LIBFPTR_ERROR_MARKING_CODE_CONFLICT,
    LIBFPTR_ERROR_INVALID_RECORDS_ID,
    LIBFPTR_ERROR_INVALID_SIGNATURE,
    LIBFPTR_ERROR_INVALID_EXCISE_SUM,
    LIBFPTR_ERROR_NO_DOCUMENTS_FOUND_IN_JOURNAL,
    LIBFPTR_ERROR_INVALID_SCRIPT_TYPE,
    LIBFPTR_ERROR_INVALID_SCRIPT_NAME,
    LIBFPTR_ERROR_INVALID_POSITIONS_COUNT_WITH_1162,
    LIBFPTR_ERROR_INVALID_UC_COUNTER,
    LIBFPTR_ERROR_INVALID_UC_TAG,
    LIBFPTR_ERROR_INVALID_UC_IDX,
    LIBFPTR_ERROR_INVALID_UC_SIZE,
    LIBFPTR_ERROR_INVALID_UC_CONFIG,
    LIBFPTR_ERROR_CONNECTION_LOST,
    LIBFPTR_ERROR_UNIVERSAL_COUNTERS_FAULT,
    LIBFPTR_ERROR_INVALID_TAX_SUM,
    LIBFPTR_ERROR_INVALID_MARKING_CODE_TYPE,
    LIBFPTR_ERROR_LICENSE_HARD_FAULT,
    LIBFPTR_ERROR_LICENSE_INVALID_SIGN,
    LIBFPTR_ERROR_LICENSE_INVALID_SERIAL,
    LIBFPTR_ERROR_LICENSE_INVALID_TIME,
    LIBFPTR_ERROR_DOCUMENT_CANCELED,
    LIBFPTR_ERROR_INVALID_SCRIPT_PARAMS,
    LIBFPTR_ERROR_CLICHE_TOO_LONG,
    LIBFPTR_ERROR_COMMODITIES_TABLE_FAULT,
    LIBFPTR_ERROR_COMMODITIES_TABLE,
    LIBFPTR_ERROR_COMMODITIES_TABLE_INVALID_TAG,
    LIBFPTR_ERROR_COMMODITIES_TABLE_INVALID_TAG_SIZE,
    LIBFPTR_ERROR_COMMODITIES_TABLE_NO_TAG_DATA,
    LIBFPTR_ERROR_COMMODITIES_TABLE_NO_FREE_MEMORY,
    LIBFPTR_ERROR_INVALID_CACHE,
    LIBFPTR_ERROR_SCHEDULER_NOT_READY,
    LIBFPTR_ERROR_SCHEDULER_INVALID_TASK,
    LIBFPTR_ERROR_MINIPOS_NO_POSITION_PAYMENT,
    LIBFPTR_ERROR_MINIPOS_COMMAND_TIME_OUT,
    LIBFPTR_ERROR_MINIPOS_MODE_FR_DISABLED,
    LIBFPTR_ERROR_ENTRY_NOT_FOUND_IN_OTP,
    LIBFPTR_ERROR_EXCISABLE_COMMODITY_WITHOUT_EXCISE,

    LIBFPTR_ERROR_BASE_MARKING = 400,
    LIBFPTR_ERROR_MARKING_CODE_VALIDATION_IN_PROGRESS,
    LIBFPTR_ERROR_NO_CONNECTION_WITH_SERVER,
    LIBFPTR_ERROR_MARKING_CODE_VALIDATION_CANCELED,
    LIBFPTR_ERROR_INVALID_MARKING_CODE_STATUS,
    LIBFPTR_ERROR_INVALID_GS1,
    LIBFPTR_ERROR_MARKING_WORK_DENIED,
    LIBFPTR_ERROR_MARKING_WORK_TEMPORARY_BLOCKED,
    LIBFPTR_ERROR_MARKS_OVERFLOW,
    LIBFPTR_ERROR_INVALID_MARKING_CODE,
    LIBFPTR_ERROR_INVALID_STATE,
    LIBFPTR_ERROR_OFD_EXCHANGE,
    LIBFPTR_ERROR_INVALID_MEASUREMENT_UNIT,
    LIBFPTR_ERROR_OPERATION_DENIED_IN_CURRENT_FFD,
    LIBFPTR_ERROR_MARKING_OPERATION_DENIED,
    LIBFPTR_ERROR_NO_DATA_TO_SEND,
    LIBFPTR_ERROR_NO_MARKED_POSITION,
    LIBFPTR_ERROR_HAS_NOT_SEND_NOTICES,
    LIBFPTR_ERROR_UPDATE_KEYS_REQUIRED,
    LIBFPTR_ERROR_UPDATE_KEYS_SERVICE,
    LIBFPTR_ERROR_MARK_NOT_CHECKED,
    LIBFPTR_ERROR_MARK_CHECK_TIMEOUT_EXPIRED,
    LIBFPTR_ERROR_MARKING_END = 499,

    LIBFPTR_ERROR_BASE_WEB = 500,
    LIBFPTR_ERROR_RECEIPT_PARSE_ERROR,
    LIBFPTR_ERROR_INTERRUPTED_BY_PREVIOUS_ERRORS,
    LIBFPTR_ERROR_DRIVER_SCRIPT_ERROR,
    LIBFPTR_ERROR_VALIDATE_FUNC_NOT_FOUND,
    LIBFPTR_ERROR_WEB_FAIL,
    LIBFPTR_ERROR_WEB_END = 599,

    LIBFPTR_ERROR_BASE_RPC = 600,
    LIBFPTR_ERROR_RCP_SERVER_BUSY,
    LIBFPTR_ERROR_RCP_SERVER_VERSION,
    LIBFPTR_ERROR_RCP_SERVER_EXCHANGE,
    LIBFPTR_ERROR_RPC_END = 699,

    LIBFPTR_ERROR_USERS_SCRIPTS_BASE = 1000,
    LIBFPTR_ERROR_USERS_SCRIPTS_END = 1999,
}

export const ErrorCodes = {
  0: "Ошибок нет",
  1: "Соединение не установлено",
  2: "Нет связи",
  3: "Порт занят",
  4: "Порт недоступен",
  5: "Некорректные данные от устройства",
  6: "Внутренняя ошибка библиотеки",
  7: "Неподдерживаемое преобразование типа параметра",
  8: "Не найден обязательный параметр",
  9: "Некорректные настройки",
  10: "Драйвер не настроен",
  11: "Не поддерживается в данной версии (драйвера или ККТ)",
  12: "Не поддерживается в данном режиме",
  13: "Нeкорректное значение параметра",
  14: "Не удалось загрузить библиотеку",
  15: "Неизвестная ошибка",
  16: "Неверная цена (сумма)",
  17: "Неверное количество",
  18: "Переполнение счетчика наличности",
  19: "Невозможно сторно последней операции",
  20: "Сторно по коду невозможно",
  21: "Невозможен повтор последней операции",
  22: "Повторная скидка на операцию невозможна",
  23: "Невозможно начислить скидку/надбавку",
  24: "Неверный код товара",
  25: "Неверный штрихкод товара",
  26: "Неверный формат команды",
  27: "Неверная длина",
  28: "ККТ заблокирована в режиме ввода даты",
  29: "Требуется подтверждение ввода даты",
  30: "Нет больше данных",
  31: "Нет подтверждения или отмены продажи",
  32: "Отчет о закрытии смены прерван",
  33: "Отключение контроля наличности невозможно (не настроены необходимые типы оплаты)",
  34: "Вход в режим заблокирован",
  35: "Проверьте дату и время",
  36: "Переданные дата/время меньше даты/времени последнего фискального документа",
  37: "Невозможно закрыть архив",
  38: "Товар не найден",
  39: "Весовой штрихкод с количеством <> 1.000",
  40: "Переполнение буфера чека",
  41: "Недостаточное количество товара",
  42: "Сторнируемое количество больше проданного",
  43: "Товар не найден",
  44: "Нет бумаги",
  45: "Открыта крышка",
  46: "Нет связи с принтером чеков",
  47: "Механическая ошибка печатающего устройства",
  48: "Неверный тип чека",
  49: "Недопустимое целевое устройство",
  50: "Нет места в массиве картинок/штрихкодов",
  51: "Неверный номер картинки/штрихкода (картинка/штрихкод отсутствует)",
  52: "Сумма не наличных платежей превышает сумму чека",
  53: "Накопление меньше суммы возврата или аннулирования",
  54: "Переполнение суммы платежей",
  55: "Предыдущая операция незавершена",
  56: "Ошибка GSM- модуля",
  57: "Неверная величина скидки / надбавки",
  58: "Операция после скидки / надбавки невозможна",
  59: "Неверная секция",
  60: "Неверный вид оплаты",
  61: "Переполнение при умножении",
  62: "Операция запрещена в таблице настроек",
  63: "Переполнение итога чека",
  64: "Открыт чек аннулирования – операция невозможна",
  65: "Переполнение буфера ЭЖ",
  66: "Чек оплачен не полностью",
  67: "Открыт чек возврата – операция невозможна",
  68: "Смена превысила 24 часа",
  69: "Открыт чек продажи – операция невозможна",
  70: "Переполнение ФП",
  71: "Неверный пароль",
  72: "Идет обработка ЭЖ",
  73: "Смена закрыта - операция невозможна",
  74: "Неверный номер таблицы",
  75: "Неверный номер ряда",
  76: "Неверный номер поля",
  77: "Неверная дата и/или время",
  78: "Неверная сумма сторно",
  79: "Подсчет суммы сдачи невозможен",
  80: "В ККТ нет денег для выплаты",
  81: "Чек закрыт – операция невозможна",
  82: "Чек открыт – операция невозможна",
  83: "Смена открыта, операция невозможна",
  84: "Серийный номер / MAC- адрес уже задан",
  85: "Исчерпан лимит перерегистраций",
  86: "Неверный номер смены",
  87: "Недопустимый серийный номер ККТ",
  88: "Недопустимый РНМ и/или ИНН",
  89: "ККТ не зарегистрирована",
  90: "Не задан серийный номер",
  91: "Нет отчетов",
  92: "Режим не активизирован",
  93: "Данные документа отсутствуют",
  94: "Некорректный код защиты / лицензия или номер",
  95: "Требуется выполнение общего гашения",
  96: "Команда не разрешена введенными кодами защиты / лицензиями ККТ",
  97: "Невозможна отмена скидки/надбавки",
  98: "Невозможно закрыть чек данным типом оплаты",
  99: "Неверный номер маршрута",
  100: "Неверный номер начальной зоны",
  101: "Неверный номер конечной зоны",
  102: "Неверный тип тарифа",
  103: "Неверный тариф",
  104: "Ошибка обмена с фискальным модулем",
  105: "Необходимо провести профилактические работы",
  106: "Неверные номера смен в ККТ и ФН",
  107: "Нет устройства, обрабатывающего данную команду",
  108: "Нет связи с внешним устройством",
  109: "Ошибочное состояние ТРК",
  110: "Недопустимое кол- во позиций в чеке",
  111: "Ошибочный номер ТРК",
  112: "Неверный делитель",
  113: "Активация данного ФН в составе данной ККТ невозможна",
  114: "Перегрев головки принтера",
  115: "Ошибка обмена с ФН на уровне интерфейса I2C",
  116: "Ошибка формата передачи ФН",
  117: "Неверное состояние ФН",
  118: "Неисправимая ошибка ФН",
  119: "Ошибка КС ФН",
  120: "Закончен срок эксплуатации ФН",
  121: "Архив ФН переполнен",
  122: "В ФН переданы неверная дата или время",
  123: "В ФН нет запрошенных данных",
  124: "Переполнение ФН (итог чека / смены)",
  125: "Буфер переполнен",
  126: "Невозможно напечатать вторую фискальную копию",
  127: "Требуется гашение ЭЖ",
  128: "Некорректная сумма налога",
  129: "Начисление налога на последнюю операцию невозможно",
  130: "Неверный номер ФН",
  131: "Сумма сторно налога больше суммы зарегистрированного налога данного типа",
  132: "Операция невозможна, недостаточно питания",
  133: "Некорректное значение параметров команды ФН",
  134: "Превышение размеров TLV данных ФН",
  135: "Нет транспортного соединения ФН",
  136: "Исчерпан ресурс КС ФН",
  137: "Ресурс хранения ФД исчерпан",
  138: "Сообщение от ОФД не может быть принято ФН",
  139: "В ФН есть неотправленные ФД",
  140: "Исчерпан ресурс ожидания передачи сообщения в ФН",
  141: "Продолжительность смены ФН более 24 часов",
  142: "Неверная разница во времени между двумя операциями ФН",
  143: "Некорректная СНО",
  144: "Недопустимый номер ставки налога",
  145: "Недопустимый тип оплаты товара",
  146: "Недопустимый тип кода товара",
  147: "Недопустима регистрация подакцизного товара",
  148: "Ошибка программирования реквизита",
  149: "Неверный тип счетчика",
  150: "Ошибка отрезчика",
  151: "Снятие отчета прервалось",
  152: "Недопустимое значение отступа слева",
  153: "Недопустимое значение выравнивания",
  154: "Недопустимое значение режима работы с налогом",
  155: "Файл не найден или неверный формат",
  156: "Размер картинки слишком большой",
  157: "Не удалось сформировать штрихкод",
  158: "Неразрешенные реквизиты",
  159: "Ошибка интерфейса ФН",
  160: "Дублирование данных",
  161: "Не указаны обязательные реквизиты",
  162: "Ошибка чтения документа из ФН",
  163: "Переполнение чисел с плавающей точкой",
  164: "Неверное значение параметра ККТ",
  165: "Внутренняя ошибка ККТ",
  166: "ФН не найден",
  167: "Невозможно записать реквизит агента",
  168: "Недопустимое сочетания реквизитов 1002 и 1056",
  169: "Недопустимое сочетания реквизитов 1002 и 1017",
  170: "Ошибка скриптового движка ККТ",
  171: "Неверный номер пользовательской ячейки памяти",
  172: "Кассир не зарегистрирован",
  173: "Отчет о регистрации ККТ прерван",
  174: "Отчет о закрытии ФН прерван",
  175: "Отчет об открытии смены прерван",
  176: "Отчет о состоянии расчетов прерван",
  177: "Закрытие чека прервано",
  178: "Получение документа из ФН прервано",
  179: "Сбой часов",
  180: "Сбой памяти",
  181: "Сбой микросхемы",
  182: "Ошибка шаблонов документов",
  183: "Недопустимое значение MAC- адреса",
  184: "Неверный тип (номер) шаблона",
  185: "Загруженные шаблоны повреждены или отсутствуют",
  186: "Несовместимая версия загруженных шаблонов",
  187: "Ошибка в формате клише",
  188: "Требуется перезагрузка ККТ",
  189: "Подходящие лицензии не найдены",
  190: "Неверная версия ФФД",
  191: "Параметр доступен только для чтения",
  192: "Неверный тип кода товара",
  193: "Неверное значение GTIN",
  194: "Отрицательный результат математической операции",
  195: "Недопустимое сочетание реквизитов",
  196: "Ошибка регистрации кассира",
  197: "Данный канал Интернет отсутствует в ККТ",
  198: "Дата и время не синхронизированы",
  199: "Ошибка электронного журнала",
  200: "Документ открыт - операция невозможна",
  201: "Документ закрыт - операция невозможна",
  202: "Нет места для сохранения лицензий",
  203: "Произошла критичная ошибка, документ необходимо отменить",
  204: "Регистры ККТ еще не инициализированы",
  205: "Требуется регистрация итога",
  206: "Сбой таблицы настроек",
  207: "Сбой счетчиков и регистров ККТ",
  208: "Сбой пользовательской памяти",
  209: "Сбой сервисных регистров",
  210: "Сбой реквизитов ККТ",
  211: "ККТ уже в режиме обновления конфигурации",
  212: "Конфигурация не прошла проверку",
  213: "Аппаратный канал отсутствует, выключен или ещё не проинициализирован",
  214: "Сетевой интерфейс не подключен, или на нём не получен IP-адрес",
  215: "Недопустимое сочетание реквизитов 1212 и 1030",
  216: "Некорректный признак способа расчета",
  217: "Некорректный признак предмета расчета",
  218: "Ошибка синхронизации времени",
  219: "В одном чеке одновременно не может быть позиций с НДС 18% (18/118) и НДС 20% (20/120)",
  220: "Картинка не закрыта",
  221: "Сетевой интерфейс занят",
  222: "Неверный номер картинки",
  223: "Ошибка проверки контейнера",
  224: "Архив ФН закрыт",
  225: "Нужно выполнить регистрацию / перерегистрацию",
  226: "Операция невозможна, идет обновление ПО ККТ",
  227: "Неверный итог чека",
  228: "Запрещена одновременная передача КМ и реквизита 1162",
  229: "Набор записей по заданному идентификатору не найден",
  230: "Ошибка цифровой подписи",
  231: "Некорректная сумма акциза",
  232: "Заданный диапазон документов не найден в БД документов",
  233: "Неподдерживаемый тип скрипта",
  234: "Некорректный идентификатор скрипта",
  235: "Кол-во позиций с реквизитом 1162 в автономном режиме превысило разрешенный лимит",
  236: "Универсальный счетчик с заданными параметрами недоступен",
  237: "Неподдерживаемый тег для универсальных счетчиков",
  238: "Некорректный индекс для универсальных счетчиков",
  239: "Неверный размер универсального счетчика",
  240: "Неверная конфигурация универсальных счетчиков",
  241: "Соединение с ККТ потеряно",
  242: "Ошибка универсальных счетчиков",
  243: "Некорректная сумма налога",
  244: "Некорректное значение типа кода маркировки",
  245: "Аппаратная ошибка при сохранении лицензии",
  246: "Подпись лицензии некорректна",
  247: "Лицензия не подходит для данной ККТ",
  248: "Срок действия лицензии истёк",
  249: "Документ был отменен",
  250: "Некорректные параметры скрипта",
  251: "Длина клише превышает максимальное значение",
  252: "Ошибка таблицы товаров",
  253: "Общая ошибка таблицы товаров",
  254: "Некорректный тег для таблицы товаров",
  255: "Некорректный размер тега для таблицы товаров",
  256: "Нет данных по тегу в таблице товаров",
  257: "Нет места в динамической области памяти таблицы товаров",
  258: "Ошибка чтения/записи данных кеша",
  259: "Функции планировщика заданий не доступны",
  260: "Неизвестный тип задания планировщика",
  261: "Отсутствует позиция оплаты",
  262: "Таймаут выполнения команды истек",
  263: "Режим ФР выключен",
  264: "Не найдена запись в OTP",
  265: "Подакцизный товар без акциза зарегистрирован в чеке",
  401: "Процедура проверки КМ уже запущена",
  402: "Ошибка соединения с сервером",
  403: "Процедура проверки КМ прервана",
  404: "Некорректное значение статуса КМ",
  405: "Неверный код GS1",
  406: "Запрещена работа с маркированным товарами",
  407: "Работа с маркированными товарами временно заблокирована",
  408: "Переполнена таблица хранения КМ",
  409: "Некорректный код маркировки",
  410: "Неверное состояние",
  411: "Ошибка обмена с сервером ОФД или ИСМ",
  412: "Некорректное значение единиц измерения",
  413: "Операция не разрешена в данной версии ФФД",
  414: "Операция не разрешена, при регистрации не был установлен признак ТМТ",
  415: "Нет данных для отправки",
  416: "Нет маркированных позиций в чеке",
  417: "Имеются неотправленные уведомления",
  418: "Требуется повторное проведение процедуры обновления ключей",
  419: "Ошибка сервиса обновления ключей проверки КМ",
  420: "КМ не проверен в ФН",
  421: "Истёк таймаут проверки КМ",
  422: "Данный КМ отсутствует в таблице",
  501: "Ошибка парсинга чека / запроса",
  502: "Выполнение прервано из-за предыдущих ошибок",
  503: "Ошибка скрипта драйвера",
  504: "Функция проверки задания не найдена",
  505: "Выполняется проверка КМ",
} as const
